---
ID: "a5e9bd98-8177-414f-85dc-1e5991e50fc9"
Parent: "bbfcc196-fbe4-4066-b01e-deaa055fa1aa"
Template: "bbfcc196-fbe4-4066-b01e-deaa055fa1aa"
Path: /sitecore/templates/Feature/Solution Engineers/Footer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250220T000432Z
    - ID: "4e54dbdf-9eac-4242-bff7-45e3b944643a"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "87e72b4b-dca3-4e10-970a-62400c46a422"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250220T114359Z
