---
ID: "54c03347-b21a-456b-8fad-689bd379fb8c"
Parent: "c731f1d5-c533-4348-bae1-4c3a6267b4d6"
Template: "c731f1d5-c533-4348-bae1-4c3a6267b4d6"
Path: /sitecore/templates/Feature/Solution Engineers/Rendering Configurations/Slide Title Configuration/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0ed612f2-6657-4dbe-b933-ed7662a9cf1f"
      Hint: PrefixAnimation
      Value: "{3F13CD60-4A67-4511-9A2B-879FB2BB0B36}"
    - ID: "25b9bd45-cdc7-4bce-a20e-ec9e9643b745"
      Hint: SuffixAnimation
      Value: "{F3466715-B4F6-4001-82CA-59486FEC0214}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250322T214906Z
    - ID: "3bb4c66a-c97c-48e4-9b26-8b2fc8baa337"
      Hint: PrefixAnimationDelay
      Value: "{6109BE38-25D7-4EF7-9551-E572CAB12BAA}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c7df5b50-827f-4e53-aa4a-5deb80abee66"
    - ID: "93b9b5f4-3403-4905-b8c2-2f5d0b52fae4"
      Hint: SuffixAnimationDelay
      Value: "{6109BE38-25D7-4EF7-9551-E572CAB12BAA}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250324T021115Z
    - ID: "db81f3a6-5362-4ec0-a02d-96fdb5b7522f"
      Hint: SuffixImage
      Value: |
        <image mediaid="{F0813138-85E8-4DDE-B4E0-B1D9DCC3CA8D}" />
    - ID: "ec4a5ab1-41c3-4efd-be19-1cd64dbb9c17"
      Hint: PrefixImage
      Value: |
        <image mediaid="{F0813138-85E8-4DDE-B4E0-B1D9DCC3CA8D}" />
