---
ID: "2aa27328-115b-4f0f-a9e3-6ae07f9255ed"
Parent: "78a994e3-4e7e-462b-8735-1cb0a7016a31"
Template: "c731f1d5-c533-4348-bae1-4c3a6267b4d6"
Path: /sitecore/content/default/templates/Presentation/Rendering Configurations/Slide Title Configuration
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0ed612f2-6657-4dbe-b933-ed7662a9cf1f"
      Hint: PrefixAnimation
      Value: "{95F2F894-1568-415A-9270-43C7C084A665}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250322T214442Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "375ab87f-069f-4d11-831a-9c72adc65931"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250327T005011Z
    - ID: "ec4a5ab1-41c3-4efd-be19-1cd64dbb9c17"
      Hint: PrefixImage
      Value: |
        <image mediaid="{F0813138-85E8-4DDE-B4E0-B1D9DCC3CA8D}" alt="FERRE6" height="" width="" hspace="" vspace="" />
