---
ID: "6c70e8e0-98d4-4c2b-8d9e-3ffa85e96311"
Parent: "ef8e64c6-16c8-4a88-aafd-f4b00d4377e1"
Template: "ef8e64c6-16c8-4a88-aafd-f4b00d4377e1"
Path: /sitecore/templates/Project/lenovo/Rendering Parameters/LenovoQuickLinkItem Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c2841472-ba2e-4692-8676-13f6d1df2b66"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251116T233411Z
