---
ID: "91a9e4a5-fbcf-4c84-8441-811336522324"
Parent: "329d35d8-2267-4560-90b7-1b33211b0173"
Template: "329d35d8-2267-4560-90b7-1b33211b0173"
Path: /sitecore/templates/Project/lenovo/LenovoDealRegistrationsCard/__Standard Values
SharedFields:
- ID: "10bf37a1-a4cc-4398-b161-af8300681715"
  Hint: BidRequestHistoric
  Value: (58)
- ID: "17ac0b45-09eb-4440-a692-6fdaeadede16"
  Hint: LeadsValue
  Value: 23
- ID: "4d10caff-e8fe-4ad7-a41e-0f10a5578b19"
  Hint: DealRegPending
  Value: (190K)
- ID: "65c4af4b-f8d5-4a7d-a206-4b33e1a88408"
  Hint: BidRequestValue
  Value: 226
- ID: "6a3718aa-78b0-4ccc-9f5f-6eb6a0be4a7d"
  Hint: DealRegValue
  Value: 610K
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "0cd79afb-2c80-4857-863b-9fd31bea8a64"
- ID: "f25adace-99b2-49ea-890d-97fbffff2027"
  Hint: InfrastructureValue
  Value: 2
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "07f802d1-f2e6-4af0-bad5-3c4cd204c10e"
      Hint: ButtonText
      Value: View Deals
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T003357Z
    - ID: "31dcee8e-774d-4938-9938-c40502cc7a72"
      Hint: LeadsStatus
      Value: New
    - ID: "432dbd71-4d46-4b4b-ad11-284d0c136925"
      Hint: BidRequestLabel
      Value: Bid Requests
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "741ac966-bccf-4e63-96e1-3d18a1b608fb"
      Hint: DealRegLabel
      Value: Deal Registrations
    - ID: "75d71bf0-0735-484b-86d4-ef39f62f618d"
      Hint: DealRegSubmitted
      Value: (420K)
    - ID: "864e5391-7360-4556-b638-25d884aef803"
      Hint: InfrastructureLabel
      Value: Infrastructure
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ec032e26-7380-4af7-800a-540186d0475d"
    - ID: "9b5f5826-e884-40cc-b189-2ddddd6acba3"
      Hint: Heading
      Value: Deal Registrations and Bid Requests
    - ID: "ab06d809-6442-41a5-b51b-fa4fc59bf32f"
      Hint: InfrastructureStatus
      Value: News
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "cd4fc4ba-be43-4985-ac28-05be05d11991"
      Hint: LeadsLabel
      Value: Leads
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T003643Z
