// tailwind.config.mjs
/** @type {import('tailwindcss').Config} */

const config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    // If classes can appear in a lib:
    // './node_modules/@sitecore-content-sdk/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    // gaps
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-5',

    // text sizes
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-7xl',
    'text-8xl',
    'text-9xl',

    // common utilities
    'w-full',
    'w-[50%]',
    'basis-full',
    'basis-0',
    'grow',
    'no-underline',

    // responsive margin presets
    'ml-0',
    'mr-0',
    'mx-0',
    'ml-auto',
    'mr-auto',
    'mx-auto',
    'sm:ml-0',
    'sm:mr-0',
    'sm:mx-0',
    'sm:ml-auto',
    'sm:mr-auto',
    'sm:mx-auto',
    'md:ml-0',
    'md:mr-0',
    'md:mx-0',
    'md:ml-auto',
    'md:mr-auto',
    'md:mx-auto',
    'lg:ml-0',
    'lg:mr-0',
    'lg:mx-0',
    'lg:ml-auto',
    'lg:mr-auto',
    'lg:mx-auto',
    'xl:ml-0',
    'xl:mr-0',
    'xl:mx-0',
    'xl:ml-auto',
    'xl:mr-auto',
    'xl:mx-auto',
    '2xl:ml-0',
    '2xl:mr-0',
    '2xl:mx-0',
    '2xl:ml-auto',
    '2xl:mr-auto',
    '2xl:mx-auto',
    // Width percentages
    'w-[1%]',
    'w-[2%]',
    'w-[3%]',
    'w-[4%]',
    'w-[5%]',
    'w-[6%]',
    'w-[7%]',
    'w-[8%]',
    'w-[9%]',
    'w-[10%]',
    'w-[11%]',
    'w-[12%]',
    'w-[13%]',
    'w-[14%]',
    'w-[15%]',
    'w-[16%]',
    'w-[17%]',
    'w-[18%]',
    'w-[19%]',
    'w-[20%]',
    'w-[21%]',
    'w-[22%]',
    'w-[23%]',
    'w-[24%]',
    'w-[25%]',
    'w-[26%]',
    'w-[27%]',
    'w-[28%]',
    'w-[29%]',
    'w-[30%]',
    'w-[31%]',
    'w-[32%]',
    'w-[33%]',
    'w-[34%]',
    'w-[35%]',
    'w-[36%]',
    'w-[37%]',
    'w-[38%]',
    'w-[39%]',
    'w-[40%]',
    'w-[41%]',
    'w-[42%]',
    'w-[43%]',
    'w-[44%]',
    'w-[45%]',
    'w-[46%]',
    'w-[47%]',
    'w-[48%]',
    'w-[49%]',
    'w-[50%]',
    'w-[51%]',
    'w-[52%]',
    'w-[53%]',
    'w-[54%]',
    'w-[55%]',
    'w-[56%]',
    'w-[57%]',
    'w-[58%]',
    'w-[59%]',
    'w-[60%]',
    'w-[61%]',
    'w-[62%]',
    'w-[63%]',
    'w-[64%]',
    'w-[65%]',
    'w-[66%]',
    'w-[67%]',
    'w-[68%]',
    'w-[69%]',
    'w-[70%]',
    'w-[71%]',
    'w-[72%]',
    'w-[73%]',
    'w-[74%]',
    'w-[75%]',
    'w-[76%]',
    'w-[77%]',
    'w-[78%]',
    'w-[79%]',
    'w-[80%]',
    'w-[81%]',
    'w-[82%]',
    'w-[83%]',
    'w-[84%]',
    'w-[85%]',
    'w-[86%]',
    'w-[87%]',
    'w-[88%]',
    'w-[89%]',
    'w-[90%]',
    'w-[91%]',
    'w-[92%]',
    'w-[93%]',
    'w-[94%]',
    'w-[95%]',
    'w-[96%]',
    'w-[97%]',
    'w-[98%]',
    'w-[99%]',
    'w-[100%]',

    // Height percentages
    'h-[1%]',
    'h-[2%]',
    'h-[3%]',
    'h-[4%]',
    'h-[5%]',
    'h-[6%]',
    'h-[7%]',
    'h-[8%]',
    'h-[9%]',
    'h-[10%]',
    'h-[11%]',
    'h-[12%]',
    'h-[13%]',
    'h-[14%]',
    'h-[15%]',
    'h-[16%]',
    'h-[17%]',
    'h-[18%]',
    'h-[19%]',
    'h-[20%]',
    'h-[21%]',
    'h-[22%]',
    'h-[23%]',
    'h-[24%]',
    'h-[25%]',
    'h-[26%]',
    'h-[27%]',
    'h-[28%]',
    'h-[29%]',
    'h-[30%]',
    'h-[31%]',
    'h-[32%]',
    'h-[33%]',
    'h-[34%]',
    'h-[35%]',
    'h-[36%]',
    'h-[37%]',
    'h-[38%]',
    'h-[39%]',
    'h-[40%]',
    'h-[41%]',
    'h-[42%]',
    'h-[43%]',
    'h-[44%]',
    'h-[45%]',
    'h-[46%]',
    'h-[47%]',
    'h-[48%]',
    'h-[49%]',
    'h-[50%]',
    'h-[51%]',
    'h-[52%]',
    'h-[53%]',
    'h-[54%]',
    'h-[55%]',
    'h-[56%]',
    'h-[57%]',
    'h-[58%]',
    'h-[59%]',
    'h-[60%]',
    'h-[61%]',
    'h-[62%]',
    'h-[63%]',
    'h-[64%]',
    'h-[65%]',
    'h-[66%]',
    'h-[67%]',
    'h-[68%]',
    'h-[69%]',
    'h-[70%]',
    'h-[71%]',
    'h-[72%]',
    'h-[73%]',
    'h-[74%]',
    'h-[75%]',
    'h-[76%]',
    'h-[77%]',
    'h-[78%]',
    'h-[79%]',
    'h-[80%]',
    'h-[81%]',
    'h-[82%]',
    'h-[83%]',
    'h-[84%]',
    'h-[85%]',
    'h-[86%]',
    'h-[87%]',
    'h-[88%]',
    'h-[89%]',
    'h-[90%]',
    'h-[91%]',
    'h-[92%]',
    'h-[93%]',
    'h-[94%]',
    'h-[95%]',
    'h-[96%]',
    'h-[97%]',
    'h-[98%]',
    'h-[99%]',
    'h-[100%]',
    // pattern-based
    {
      // allow layout/positioning with suffixes: flex-row, flex-col, gap-*, basis-*, order-*
      pattern:
        /^(?:basis-|order-|flex-|inline-|block|hidden|table|static|fixed|relative|absolute|gap-).*/,
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
    {
      // all margin shorthands: m-, mt-, mr-, mb-, ml-, mx-, my-
      pattern: /^m[trblxy]?-.*/,
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
  ],
  theme: {
    extend: {
      colors: {
        // Primary
        'primary-color-1': 'var(--tw-primary-color-1)',
        'primary-color-2': 'var(--tw-primary-color-2)',
        'primary-color-3': 'var(--tw-primary-color-3)',
        // Secondary
        'secondary-color-1': 'var(--tw-secondary-color-1)',
        'secondary-color-2': 'var(--tw-secondary-color-2)',
        'secondary-color-3': 'var(--tw-secondary-color-3)',
        'secondary-color-4': 'var(--tw-secondary-color-4)',
        // Neutral
        'neutral-color-black': 'var(--tw-black)',
        'neutral-color-white': 'var(--tw-white)',
        'neutral-color-dark-gray': 'var(--tw-dark-gray)',
        'neutral-color-mid-tone-gray': 'var(--tw-mid-tone-gray)',
        'neutral-color-light-gray': 'var(--tw-light-gray)',
        'neutral-color-very-light-gray': 'var(--tw-very-light-gray)',
        'neutral-color-ultra-light-gray': 'var(--tw-ultra-light-gray)',
        'neutral-color-near-white-gray': 'var(--tw-near-white-gray)',
      },
    },
  },
  // plugins: [require('@tailwindcss/aspect-ratio')],
};

export default config;
