---
ID: "939e8857-d7f3-4323-b7a3-d0fce3431224"
Parent: "bc2a73fe-be78-4c07-a5d2-9c9d3f3570bb"
Template: "bc2a73fe-be78-4c07-a5d2-9c9d3f3570bb"
Path: /sitecore/templates/Project/lenovo/Rendering Parameters/LenovoSolutionHubHeader Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "61803e28-810a-4ec5-bf6f-96d6077f07b6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251112T215827Z
